name: Continuous Delivery
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀

on:
  push:
    branches: [ "main" ]

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
          path: |
            **.xml
            **.java

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/upload-artifact@v4
        with:
          name: projetozipado.zip
      - name: Display Structure of downloaded files
        run: ls -R
